<?php 
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_project',
		'title' => 'Project',
		'fields' => array (
			array (
				'key' => 'field_54d4939fd8aec',
				'label' => 'Content',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54d493a7d8aed',
				'label' => 'Title',
				'name' => 'title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54d4950c50af6',
				'label' => 'Parent Project',
				'name' => 'parent_project',
				'type' => 'page_link',
				'post_type' => array (
					0 => 'project',
				),
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_54d493acd8aee',
				'label' => 'Description',
				'name' => 'description',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_54ef03cda5b69',
				'label' => 'Further description',
				'name' => 'further_description',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_54ef392a7a751',
				'label' => 'Youtube video',
				'name' => 'youtube_video',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Paste Youtube link here',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54ef3ce837e20',
				'label' => 'Video description',
				'name' => 'video_description',
				'type' => 'textarea',
				'instructions' => 'Description of video, if required',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_54d4984200fb3',
				'label' => 'Options',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54d4985400fb4',
				'label' => 'Areas of Law',
				'name' => 'areas_of_law',
				'type' => 'taxonomy',
				'taxonomy' => 'areas_of_law',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_54d4987700fb5',
				'label' => 'Commissioners',
				'name' => 'commissioners',
				'type' => 'taxonomy',
				'taxonomy' => 'commissioner',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_54d4989a00fb6',
				'label' => 'Team',
				'name' => 'team',
				'type' => 'taxonomy',
				'taxonomy' => 'team',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_54d497ab18640',
				'label' => 'Dates',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54d496ffac379',
				'label' => 'Start Date',
				'name' => 'start_date',
				'type' => 'date_picker',
				'date_format' => 'dd/mm/yy',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_54d49711ac37a',
				'label' => 'End Date',
				'name' => 'end_date',
				'type' => 'date_picker',
				'date_format' => 'dd/mm/yy',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_54d496d5ac376',
				'label' => 'Status',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54d496e3ac377',
				'label' => 'Status',
				'name' => 'status',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54d496eaac378',
				'label' => 'Implementation Status',
				'name' => 'implementation_status',
				'type' => 'select',
				'choices' => array (
					'Pre-project' => 'Pre-project',
					'Pre-consultation' => 'Pre-consultation',
					'Consultation' => 'Consultation',
					'Analysis of responses' => 'Analysis of responses',
					'Complete' => 'Complete',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_54db35cfaa0ea',
				'label' => 'Search',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54db35deaa0eb',
				'label' => 'Keywords',
				'name' => 'keywords',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'project',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_publication',
		'title' => 'Publication',
		'fields' => array (
			array (
				'key' => 'field_54d364c4697fc',
				'label' => 'Content',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54d364a4697fa',
				'label' => 'Title',
				'name' => 'title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54d49143e9930',
				'label' => 'Reference Number',
				'name' => 'reference_number',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54d491c0e9933',
				'label' => 'Publication Date',
				'name' => 'publication_date',
				'type' => 'date_picker',
				'date_format' => 'dd/mm/yy',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_54d491d1e9934',
				'label' => 'Response Date',
				'name' => 'response_date',
				'type' => 'date_picker',
				'date_format' => 'dd/mm/yy',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_54d364ba697fb',
				'label' => 'Description',
				'name' => 'description',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_54d36479697f7',
				'label' => 'Options',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54d37be93594e',
				'label' => 'Project',
				'name' => 'project',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'project',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_54d36485697f8',
				'label' => 'Type',
				'name' => 'Type',
				'type' => 'taxonomy',
				'taxonomy' => 'document_type',
				'field_type' => 'select',
				'allow_null' => 1,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_54d364d1697fd',
				'label' => 'Files / Links',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54d364e9697fe',
				'label' => 'Files',
				'name' => 'files',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_54d49177e9931',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_54d364ee697ff',
						'label' => 'File',
						'name' => 'file',
						'type' => 'file',
						'column_width' => '',
						'save_format' => 'url',
						'library' => 'all',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_54d364f769800',
				'label' => 'Links',
				'name' => 'links',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_54d49180e9932',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_54d3650469801',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_54db7210e5fde',
				'label' => 'Search',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54db721ae5fdf',
				'label' => 'Keywords',
				'name' => 'keywords',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54d37487ca2f9',
				'label' => 'Report',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54d3749a584ba',
				'label' => 'Consultation',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54d4925dd3d43',
				'label' => 'Open Date',
				'name' => 'open_date',
				'type' => 'date_picker',
				'date_format' => 'dd/mm/yy',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_54d4926ad3d44',
				'label' => 'Close Date',
				'name' => 'close_date',
				'type' => 'date_picker',
				'date_format' => 'dd/mm/yy',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_54d374b0584bb',
				'label' => 'Other Project Documents and Downloads',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_54d374c4584bc',
				'label' => 'Project Related Documents and Downloads',
				'name' => '',
				'type' => 'tab',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'document',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
