version: '2'
services:
  wordpress:
    build: .
    volumes:
      - .:/bedrock
    env_file: .env
    environment:
      WP_ENV: development
      VIRTUAL_HOST: lawcom.docker
      SMTP_HOST: mailcatcher
      SMTP_PORT: 1025
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_HOST: mysql
#      XDEBUG_CONFIG: remote_host=172.22.5.156
    links:
      - mailcatcher
      - mysql
    depends_on:
      - mailcatcher
      - mysql
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    depends_on:
      - mysql
    environment:
      VIRTUAL_HOST: db.lawcom.docker
      PMA_USER: root
      PMA_PASSWORD: root
  mailcatcher:
    image: schickling/mailcatcher
    environment:
      VIRTUAL_HOST: mail.lawcom.docker
      VIRTUAL_PORT: 1080
volumes:
  database:
    driver: local
